config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :clubs
  resources :fields
  resources :inscriptions
  devise_for :users
  get 'inscription_welcome' => 'inscriptions#welcome_inscription'
  get 'inscription_index' => 'inscriptions#select_inscription'
  get 'admin' => 'admin#home'
  get 'search_register' => 'admin#search_register'
  get 'directors' => 'admin#manage_directors'
  get 'teams' => 'admin#teams'
  get 'coaches' => 'admin#coaches'
  get 'mosaico' => 'admin#mosaico'
  get 'analitics' => 'admin#analitics'
  get 'fields_index' => 'admin#fields'
  get 'license' => 'admin#license_creator'
  get 'inscriptions_index' => 'admin#inscriptions_index'

end

app/views/admin/analitics.html.erb
<div class="container-fluid">
	<h3 class="text-center" id="analitics">CIFRAS ACTUALES EN LA BASE DE DATOS DE LA LIGA ANTIOQUEÑA DE BALONCESTO</h3>
	<div class="row">
		<div class="col-xs-4 col-xs-offset-4">
			<table class="table table-hover">
				<tr class="info">
					<th class="text-center">ITEM</th>
					<tH class="text-center">CANTIDAD</tH>
				</tr>
				<tr>
					<th>Numero de Clubs: </th>
					<td class="text-center"><%= @clubs %></td>
				</tr>
				<tr>
					<th>Numero de Presidentes: </th>
					<td class="text-center"><%= @presidents %></td>
				</tr>
				<tr>
					<th>Numero de Managers: </th>
					<td class="text-center"><%= @managers %></td>
				</tr>
				<tr>
					<th>Numero de Canchas: </th>
					<td class="text-center"><%= @fields %></td>
				</tr>
				<tr>
					<th>Numero de Equipos Inscritos: </th>
					<td class="text-center"><%= @inscriptions %></td>
				</tr>
				<tr>
					<th>Numero de Jugadores: </th>
					<td class="text-center"><%= @players %></td>
				</tr>
				<tr>
					<th>Numero de Entrenadores: </th>
					<td class="text-center"><%= @coaches %></td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/admin/coaches.html.erb
<div class="container-fluid">
	<div class="row text-center">
		<div class="col-xs-6 col-xs-offset-3">
			<%= form_tag coaches_path, method: :get do %>
				<div class="col-xs-6 text-center">
					<%= select_tag :tournament_id, options_from_collection_for_select(Tournament.all, "id", "name", params[:tournament_id]), prompt: "Selecction el torneo", class: "form-control" %>
				</div>
				<div class="col-xs-6 text-left">
					<%= submit_tag "ENTRENADORES", name: nil, class: "btn btn-success" %>
				</div>		  		
			<% end %>
		</div>
	</div>
	<div class="row">
		<% if !@registers.blank? %>
			<div class="col-xs-12">	
				<table class="table table-hover">
					<tr class="info">
						<th class="text-center">Participante</th>
						<th class="text-center">Tipo Inscripción</th>
						<th class="text-center">Documento de Identidad</th>
						<th class="text-center">Fecha de Nacimiento</th>
						<th class="text-center">EPS</th>
						<th class="text-center">Email</th>
						<th class="text-center">Club</th>
					</tr>
					<% @registers.each do |register| %>
						<tr class="text-center">
							<td class="vert-align"><%= image_tag register.avatar.url(:thumb) %></td>
							<td class="text-left vert-align"><%= register.first_name %> <%= register.second_name %> <%= register.first_last_name %> <%= register.second_last_name %></td>
							<td class="vert-align"><%= register.register_type.name %></td>
							<td class="vert-align"><%= register.identification %></td>
							<td class="vert-align"><%= register.date_of_birth %></td>
							<td class="vert-align"><%= register.eps %></td>
							<td class="vert-align"><%= register.email %></td>
						</tr>
					<% end %>
				</table>
			</div>
		<% else %>
			<h4 class="text-center">NO SE ENCONTRÓ NINGÚN RESULTADO ASOCIADO A ESTA BUSQUEDA</h4>
		<% end %>
	</div>
</div>

app/views/admin/fields.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover">
				<tr class="info">
					<th class="text-center">Logo</th>
					<th class="text-center">Club</th>
					<th class="text-center">Tipo</th>
					<th class="text-center">Dirección</th>
					<th class="text-center">Opciones</th>
				</tr>
				<% @fields.each do |field| %>
					<tr>
						<% if field.club.avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
							<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
						<% else %>
							<td class="vert-align text-center"><%= image_tag field.club.avatar.url(:thumb) %></td>
						<% end %>
						<td class="vert-align text-center"><%= field.club.name %></td>
						<td class="vert-align text-center"><%= field.field_type.humanize %></td>
						<td class="vert-align text-center"><%= field.address %></td>
						<td class="vert-align text-center"><%= link_to 'Ver Horarios', field, class: "btn btn-info" %></td>
					</tr>
				<% end %>
				</table>
		</div>
	</div>
</div>

app/views/admin/home.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<%= link_to 'Buscar Registro', search_register_path, class: "btn btn-info" %>
			<%= link_to 'Clubes y Directivos', directors_path, class: "btn btn-info" %>
		</div>		
	</div>
</div>

app/views/admin/inscriptions_index.html.erb
Mostrar todas las inscripciones

<div class="container-fluid">
	<div class="row">
		<table class="table table-hover">
			<tr>
				<th class="text-center">ESCUDO</th>
				<th class="text-center">NOMBRE</th>
				<th class="text-center">TORNEO</th>
				<th class="text-center">CARNETIZADO</th>	
				<th class="text-center">OPCIONES</th>			
			</tr>
			<% @inscriptions.each do |inscription| %>
				<tr>
					<% if inscription.club.avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
						<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
					<% else %>
						<td class="vert-align text-center"><%= image_tag inscription.club.avatar.url(:thumb) %></td>
					<% end %>
					<td class="text-center vert-align"><%= inscription.club.name %></td>
					<td class="text-center vert-align"><%= inscription.tournament.name %></td>
					<td class="text-center vert-align">POR DEFINIR</td>
					<td class="text-center vert-align"><%= link_to 'Generar Carnets', license_path(:inscription_id => inscription.id), class: "btn btn-success" %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/admin/license_creator.html.erb
<div class="container">
	<div class="row">
		<% @registers.each do |register| %>
			<div class="carnet_lab col-md-6">
				<p class="register_type"><%= register.register_type.name %></p>
				<p class="register_name"><%= register.first_name %> <%= register.second_name %> <%= register.first_last_name %> <%= register.second_last_name %></p>
				<p class="register_identification">Nro. Identificación: <%= register.identification %></p>
				<%= image_tag register.avatar.url(:thumb), class: "register_image" %>	
				<p class="register_date"><%= register.date_of_birth %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/manage_directors.html.erb
<div class="container-fluid">
	<div class="row text-center">
	<h4 class="text-center">SELECCIONE UNA CATEGORIA PARA CARGAR REGISTROS</h4>
	
		<%= form_tag directors_path, method: :get do %>
			<%= hidden_field_tag :club, "CLUB"  %>
	  	<div class="col-xs-2 col-xs-offset-3 action form-group">
		  	<%= submit_tag "CLUBES", name: nil, class: "btn btn-lg btn-success" %>		  		
	  	</div>
		<% end %>	
		<%= form_tag directors_path, method: :get do %>
			<%= hidden_field_tag :president, "PRESIDENT"  %>
	  	<div class=" col-xs-2 action form-group">
		  	<%= submit_tag "PRESIDENTES", name: nil, class: "btn btn-lg btn-success" %>		  		
	  	</div>
		<% end %>	
		<%= form_tag directors_path, method: :get do %>
			  <%= hidden_field_tag :manager, "MANAGER"  %>
	  	<div class="col-xs-2 action form-group">
		  	<%= submit_tag "MANAGERS", name: nil, class: "btn btn-lg  btn-success" %>		  		
	  	</div>
		<% end %>	
	</div>	

	<% if !@clubs.blank? %>
		<h2 class="text-center">CLUBES INSCRITOS EN LIGA ANTIOQUIEÑA DE BALONCESTO</h2>
		<table class="table table-hover">
			<tr class="info">
				<th class="text-center">Escudo</th>
				<th class="text-center">Nombre</th>
				<th class="text-center">Dirección</th>
				<th class="text-center">Correo</th>
				<th class="text-center">Municipio</th>
				<th class="text-center">Telefono</th>
				<th class="text-center">Celular</th>
				<th class="text-center">Ir a inscripciones</th>
			</tr>
			<% @clubs.each do |club| %>
				<tr>
					<% if club.avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
						<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
					<% else %>
						<td class="vert-align text-center"><%= image_tag club.avatar.url(:thumb) %></td>
					<% end %>
					<td class="vert-align text-center"><%= club.name %></td>
					<td class="vert-align text-center"><%= club.address %></td>
					<td class="vert-align"><%= club.email %></td>
					<td class="vert-align text-center"><%= club.municipality %></td>
					<td class="vert-align text-center"><%= club.phone %></td>
					<td class="vert-align text-center"><%= club.cellphone %></td>
					<td class="vert-align text-center"><%= link_to "Inscripciones", inscription_index_path(:club_id => club.id), class: "btn btn-info" %></td>	
				</tr>
			<% end %>
		</table>
	<% end %>

	<% if !@presidents.blank? %>
		<h2 class="text-center">PRESIDENTES INSCRITOS EN LIGA ANTIOQUIEÑA DE BALONCESTO</h2>
		<table class="table table-hover">
			<tr class="info">
				<th class="text-center">Escudo</th>
				<th class="text-center">Club</th>
				<th class="text-center">Nombre</th>
				<th class="text-center">Documento de Identidad</th>
				<th class="text-center">Telefono</th>
				<th class="text-center">FAX</th>
				<th class="text-center">Celular</th>
				<th class="text-center">Email</th>
				<th class="text-center">Ir al Club</th>
			</tr>
			<% @presidents.each do |president| %>
				<tr>
					<% if Club.find(president.club_id).avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
						<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
					<% else %>
						<td class="vert-align text-center"><%= image_tag Club.find(president.club_id).avatar.url(:thumb) %></td>
					<% end %>
					<td class="vert-align text-center"><%= president.club.name %></td>
					<td class="vert-align"><%= president.name %></td>
					<td class="vert-align text-center"><%= president.identification %></td>
					<td class="vert-align text-center"><%= president.phone %></td>
					<td class="vert-align text-center"><%= president.fax %></td>
					<td class="vert-align text-center"><%= president.cellphone %></td>
					<td class="vert-align text-center"><%= president.email %></td>
					<td class="vert-align text-center"><%= link_to "Ver Perfil del Club", Club.find(president.club_id), class: "btn btn-info" %></td>
				</tr>
			<% end %>
		</table>
	<% end %>

	<% if !@managers.blank? %>
		<h2 class="text-center">MANAGERS INSCRITOS EN LIGA ANTIOQUIEÑA DE BALONCESTO</h2>
		<table class="table table-hover">
			<tr class="info">
				<th class="text-center">Escudo</th>
				<th class="text-center">Club</th>
				<th class="text-center">Nombre</th>
				<th class="text-center">Documento de Identidad</th>
				<th class="text-center">Telefono</th>
				<th class="text-center">Celular</th>
				<th class="text-center">Email</th>
				<th class="text-center">Ir al Club</th>
			</tr>
			<% @managers.each do |manager| %>
				<tr>
					<% if Club.find(manager.club_id).avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
						<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
					<% else %>
						<td class="vert-align text-center"><%= image_tag Club.find(manager.club_id).avatar.url(:thumb) %></td>					
					<% end %>
					<td class="vert-align text-center"><%= manager.club.name %></td>
					<td class="vert-align"><%= manager.name %></td>
					<td class="vert-align text-center"><%= manager.identification %></td>
					<td class="vert-align text-center"><%= manager.phone %></td>
					<td class="vert-align text-center"><%= manager.cellphone %></td>
					<td class="vert-align text-center"><%= manager.email %></td>
					<td class="vert-align text-center"><%= link_to "Ver Perfil del Club", Club.find(manager.club_id), class: "btn btn-info" %></td>
				</tr>
			<% end %>
		</table>
	<% end %>
</	div>

app/views/admin/mosaico.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<table class="table table-hover">
				<tr class="info">
					<th class="text-center">Participante</th>
					<th class="text-center">Tipo Inscripción</th>
					<th class="text-center">Documento de Identidad</th>
					<th class="text-center">Fecha de Nacimiento</th>
					<th class="text-center">EPS</th>
					<th class="text-center">Email</th>
					<th class="text-center">Club</th>
				</tr>
				<% @registers.each do |register| %>
					<tr class="text-center">
						<td class="text-left"><%= register.first_name %> <%= register.second_name %> <%= register.first_last_name %> <%= register.second_last_name %></td>
						<td><%= register.register_type.name %></td>
						<td><%= register.identification %></td>
						<td><%= register.date_of_birth %></td>
						<td><%= register.eps %></td>
						<td><%= register.email %></td>
						<td><%= Club.find(Inscription.find(register.inscription_id).club_id).name %></td>
					</tr>					
				<% end %>
			</table>
			<div class="row">
				<% @registers.each do |register| %>
					<%= image_tag register.avatar.url(:thumb) %>			
				<% end %>				
			</div>
		</div>
	</div>
</div>

app/views/admin/search_register.html.erb
	<div class="row">
		<div class="container-fluid">
			<h4 class="text-center">INGRESE ALGUNO DE LOS DATOS A CONTINUACIÓN PARA BUSCAR UN REGISTRO EN LA BASE DE DATOS</h4>
			<%= form_tag search_register_path, method: :get do %>
				<div class="col-xs-6">
				  <div class="form-group">
				    <%= select_tag :register_type_id, options_from_collection_for_select(RegisterType.all, "id", "name", params[:register_type_id]), prompt: "Selecction el tipo de Registro", class: "form-control" %>
				  </div>
				  <div class="form-group">
			      <%= text_field_tag :identification, params[:identification], class: "form-control", placeholder: "Ingrese numero de identificación" %>
			    </div>
		  	</div>
		  	<div class="col-xs-3">
  			  <div class="form-group">
  		      <%= text_field_tag :first_name, params[:first_name], class: "form-control", placeholder: "Primer Nombre" %>
  		    </div>
  		    <div class="form-group">
  		      <%= text_field_tag :first_last_name, params[:first_last_name], class: "form-control", placeholder: "Primer Apellido" %>
  		    </div>  		    
  		  </div>
				<div class="col-xs-3">
					<div class="form-group">
					  <%= text_field_tag :second_name, params[:second_name], class: "form-control", placeholder: "Segundo Nombre" %>
					</div>  		    
  		    <div class="form-group">
  		      <%= text_field_tag :second_last_name, params[:second_last_name], class: "form-control", placeholder: "Segundo Apellido" %>
  		    </div>
		  	</div>
		  	<div class="action form-group text-center">
			  	<%= submit_tag "Buscar", name: nil, class: "btn btn-success" %>		  		
		  	</div>
			<% end %>
		</div>
		<% if !@registers.blank? %>
			<div class="col-xs-12">	
				<table class="table table-hover">
					<tr class="info">
						<th class="text-center">Imagen</th>								
						<th class="text-center">Participante</th>
						<th class="text-center">Tipo Inscripción</th>
						<th class="text-center">Documento de Identidad</th>
						<th class="text-center">Fecha de Nacimiento</th>
						<th class="text-center">EPS</th>
						<th class="text-center">Email</th>
						<th class="text-center">Torneo</th>
						<th class="text-center">Club</th>
					</tr>
					<% @registers.each do |register| %>
						<tr class="text-center">
							<td class="vert-align"><%= image_tag register.avatar.url(:thumb) %></td>
							<td class="text-left vert-align"><%= register.first_name %> <%= register.second_name %> <%= register.first_last_name %> <%= register.second_last_name %></td>
							<td class="vert-align"><%= register.register_type.name %></td>
							<td class="vert-align"><%= register.identification %></td>
							<td class="vert-align"><%= register.date_of_birth %></td>
							<td class="vert-align"><%= register.eps %></td>
							<td class="vert-align"><%= register.email %></td>
							<td class="vert-align"><%= register.inscription.tournament.name %></td>
							<td class="vert-align"><%= Club.find(Inscription.find(register.inscription_id).club_id).name %></td>
						</tr>
					<% end %>
				</table>
			</div>
		<% else %>
			<h4 class="text-center">NO SE ENCONTRÓ NINGÚN RESULTADO ASOCIADO A ESTA BUSQUEDA</h4>
		<% end %>		
	</div>

app/views/admin/teams.html.erb
<div class="container-fluid">
	<div class="row text-center">
		<h2>ELJIA UN TORNEO PARA CARGAR LOS EQUIPOS INSCRITOS</h2>
		<div class="col-xs-6 col-xs-offset-3" id="teams_by_tournament">
			<%= form_tag teams_path, method: :get do %>
				<div class="col-xs-6 text-center">
					<%= select_tag :tournament_id, options_from_collection_for_select(Tournament.all, "id", "name", params[:tournament_id]), prompt: "Selecction el torneo", class: "form-control" %>
				</div>
				<div class="col-xs-6 text-left">
					<%= submit_tag "EQUIPOS", name: nil, class: "btn btn-success" %>
				</div>		  		
			<% end %>
		</div>
	</div>
	<div class="row">
		<% if !@inscriptions.blank? %>
			<div class="col-xs-12">	
				<table class="table table-hover">
					<tr class="info">
						<th class="text-center">Escudo</th>
						<th class="text-center">Nombre</th>
						<th class="text-center">Dirección</th>
						<th class="text-center">Correo</th>
						<th class="text-center">Municipio</th>
						<th class="text-center">Telefono</th>
						<th class="text-center">Celular</th>
						<th class="text-center">Ir a inscripciones</th>
						<th class="text-center">Mosaico</th>
					</tr>
					<% @inscriptions.each do |inscription| %>
						<tr>
							<% if inscription.club.avatar.url == "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png" %>
								<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/red-not-sign-transparent-hi.png", class: "club-thumbnail" %></td>
							<% else %>
								<td class="vert-align text-center"><%= image_tag inscription.club.avatar.url(:thumb) %></td>
							<% end %>
							<td class="vert-align"><%= inscription.club.name %></td>
							<td class="vert-align"><%= inscription.club.address %></td>
							<td class="vert-align"><%= inscription.club.email %></td>
							<td class="vert-align"><%= inscription.club.municipality %></td>
							<td class="vert-align"><%= inscription.club.phone %></td>
							<td class="vert-align"><%= inscription.club.cellphone %></td>
							<td class="vert-align"><%= link_to "Inscripciones", inscription_index_path(:club_id => inscription.club.id), class: "btn btn-info" %></td>
							<td class="vert-align"><%= link_to "Mosaico", mosaico_path(:inscription_id => inscription.id), class: "btn btn-info" %></td>
						</tr>
					<% end %>
				</table>
			</div>
		<% else %>
			<h4 class="text-center">NO SE ENCONTRÓ NINGÚN RESULTADO ASOCIADO A ESTA BUSQUEDA</h4>
		<% end %>
	</div>
</div>