config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :clubs
  resources :fields
  resources :inscriptions
  devise_for :users
  get 'inscription_welcome' => 'inscriptions#welcome_inscription'
  get 'inscription_index' => 'inscriptions#select_inscription'
  get 'admin' => 'admin#home'
  get 'search_register' => 'admin#search_register'
  get 'directors' => 'admin#manage_directors'
  get 'teams' => 'admin#teams'
  get 'coaches' => 'admin#coaches'
  get 'mosaico' => 'admin#mosaico'
  get 'analitics' => 'admin#analitics'
  get 'fields_index' => 'admin#fields'
  get 'license' => 'admin#license_creator'
  get 'inscriptions_index' => 'admin#inscriptions_index'

end

app/models/inscription.rb
# == Schema Information
#
# Table name: inscriptions
#
#  id            :integer          not null, primary key
#  tournament_id :integer
#  club_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Inscription < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :club
  has_many :registers, dependent: :destroy
  accepts_nested_attributes_for :registers, :limit => 25, :reject_if => :all_blank, allow_destroy: true
  validates_associated :registers
  # after_create :send_email

  # def send_email
  # 	UserMailer.new_inscription_email(self).deliver_now
  # end
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
	before_action :authenticate_user!

	def welcome_inscription
		club_id = params[:club_id]
		tournament_id = params[:tournament_id]
		@club = Club.find(club_id)
		@tournament = Tournament.find(tournament_id)
	end

	def new		
		@tournament_id = params[:tournament_id]
		@tournament = Tournament.find(@tournament_id)
		if @tournament.expired?
			redirect_to inscription_index_path
		else
			@club_id = params[:club_id]
			@club = Club.find(@club_id)	
			@inscription = Inscription.new
			@inscription.registers.build
		end
	end

	def create
		@inscription = Inscription.new(inscription_params)
		if @inscription.save
		  redirect_to @inscription
		else
			flash[:alert] = 'Se ha encontrado un error al intentar crear esta inscripción, es muy probable que el formato de sus imagenes no sea el adecuado. Solo puede usar archivos de imagen, con extensiones como JPG o PNG, otro tipos de archivos seran rechazados. Contacte a incripcioneseventoslab@gmail.com sino puede solucionarlo.'
		  render action: :new
		end
	end

	def edit
		@tournament_id = params[:tournament_id]
		@tournament = Tournament.find(@tournament_id)

		if @tournament.expired?
			redirect_to inscription_index_path
		else
			@inscription = Inscription.find(params[:id])
			@club_id = params[:club_id]
			@club = Club.find(@club_id)
		end
	end

	def update
		@inscription = Inscription.find(params[:id])
		if @inscription.update(inscription_params)
			redirect_to @inscription
		else
			flash[:alert] = 'Se ha encontrado un error al intentar editar esta inscripción, es muy probable que el formato de sus imagenes no sea el adecuado. Solo puede usar archivos de imagen, con extensiones como JPG o PNG, otro tipos de archivos seran rechazados. Contacte a incripcioneseventoslab@gmail.com sino puede solucionarlo.'
			redirect_to :action => "edit", :tournament_id => @inscription.tournament_id, :club_id => @inscription.club.id
		end
	end

	def select_inscription
		if current_user.user?
			@inscriptions = current_user.club.inscriptions
		elsif current_user.admin?
			@club_id = params[:club_id]
			@inscriptions = Club.find(@club_id).inscriptions
		end
	end

	def show
		@inscription = Inscription.find(params[:id])
		@registers = @inscription.registers
		@club = Club.find(@inscription.club_id)
		@tournament = Tournament.find(@inscription.tournament_id)
	end

	def destroy
		@inscription = Inscription.find(params[:id])
		@inscription.destroy
		redirect_to inscription_index_path
	end

	private
		def inscription_params
  		params.require(:inscription).permit(:id,:club_id, :tournament_id, registers_attributes: [ :id, :register_type_id, :identification, :first_name, :avatar, :second_name, :first_last_name , :second_last_name , :date_of_birth, :eps, :email , :_destroy ])
		end
end

app/views/inscriptions/_inscription_form.html.erb
<%= form_for(@inscription, :html => { :id => "inscriptionForm"}) do |inscription| %>
	<%= inscription.hidden_field :club_id, value: params[:club_id] %>
	<%= inscription.hidden_field :tournament_id, value: params[:tournament_id] %>
	<%= inscription.fields_for :registers do |r| %>
		<%= render 'register_form', :register => r %>
	<% end %>
	<%= link_to_add_registers "Agregar participante", inscription, :registers %>
	<div class="actions form-group text-center">
		<%= link_to "Cancelar Inscripción", inscription_index_path(:club_id => params[:club_id]), class: "btn btn-lg btn-danger" %>
		<%= inscription.submit "Guardar Inscripción", :class => 'btn btn-lg btn-success' %>
	</div>
<% end %>

<script>
$(document).on("page:change", function() {
	$("#inscriptionForm").validate({
		errorPlacement: function(label, element) {
      label.addClass('inscription-error');
      label.insertAfter(element);
	  },
	  wrapper: 'span'
		});

	jQuery.extend(jQuery.validator.messages, {
	    required: "X"
	});
});
</script>

app/views/inscriptions/_inscription_form_edit.html.erb
<%= form_for(@inscription, :html => { :id => "inscriptionForm"}) do |inscription| %>
	<%= inscription.hidden_field :club_id, value: params[:club_id] %>
	<%= inscription.hidden_field :tournament_id, value: params[:tournament_id] %>
	<%= inscription.fields_for :registers do |r| %>
		<%= render 'register_form_edit', :register => r %>
	<% end %>
	<%= link_to_add_registers "Agregar participante", inscription, :registers %>
	<div class="actions form-group text-center">
		<%= link_to "Cancelar Inscripción", inscription_index_path(:club_id => params[:club_id]), class: "btn btn-lg btn-danger" %>
		<%= inscription.submit "Guardar Inscripción", :class => 'btn btn-lg btn-success' %>
	</div>
<% end %>

<script>
$(document).on("page:change", function() {
	$("#inscriptionForm").validate({
		errorPlacement: function(label, element) {
      label.addClass('inscription-error');
      label.insertAfter(element);
	  },
	  wrapper: 'span'
		});

	jQuery.extend(jQuery.validator.messages, {
	    required: "X"
	});
});
</script>

app/views/inscriptions/_register_form.html.erb
<fieldset class="form-group register">
	<div class="col-xs-12">
		<div class="player">
			<div class="form-group">
				<%= register.label :primer_nombre  %>
				<%= register.text_field :first_name, required: true %>
				<%= register.label :segundo_nombre %>
				<%= register.text_field :second_name %>
				<%= register.label :primer_apellido %>
				<%= register.text_field :first_last_name, required: true %>
				<%= register.label :segundo_apellido %>
				<%= register.text_field :second_last_name %>
			</div>
			<div>
				<div class="inline-register">
					<%= register.label :fotografía %>
				  <%= register.file_field :avatar, class: "inline-register", required: true %>
				</div>
				<div class="inline-register">
				 	<%= register.label :documento_de_identidad %>
					<%= register.text_field :identification, required: true %>
				</div>
			</div>
			<div class="form-group">
				<%= register.label :tipo_de_inscripción %>
				<%= register.collection_select :register_type_id, RegisterType.all, :id, :name, {prompt: 'Seleccione un tipo'}, class: "type-register", required: true %>
				<%= register.label :fecha_de_nacimiento %>
				<%= register.date_select :date_of_birth, { order: [:day, :month, :year], start_year: 1940, include_blank: true }, required: true %>
				<%= register.label :Eps %>
				<%= register.text_field :eps, required: true %>
				<%= register.label :correo_electrónico %>
				<%= register.text_field :email %>
			</div>
			<div class="form-group">					
				<%= register.hidden_field :_destroy %>
				<%= link_to "Borrar Participante", "#", class: "remove_field btn btn-danger" %>
			</div>
		</div>
	</div>
</fieldset>

app/views/inscriptions/_register_form_edit.html.erb
<fieldset class="form-group register">
	<div class="col-xs-12">
		<div class="player">
			<div class="form-group">
				<%= register.label :primer_nombre  %>
				<%= register.text_field :first_name, required: true %>
				<%= register.label :segundo_nombre %>
				<%= register.text_field :second_name %>
				<%= register.label :primer_apellido %>
				<%= register.text_field :first_last_name, required: true %>
				<%= register.label :segundo_apellido %>
				<%= register.text_field :second_last_name %>
			</div>
			<div>
				<div class="inline-register">
					<%= register.label :fotografía %>
				  <%= register.file_field :avatar, class: "inline-register" %>
				</div>
				<div class="inline-register">
				 	<%= register.label :documento_de_identidad %>
					<%= register.text_field :identification, required: true %>
				</div>
			</div>
			<div class="form-group">
				<%= register.label :tipo_de_inscripción %>
				<%= register.collection_select :register_type_id, RegisterType.all, :id, :name, {prompt: 'Seleccione un tipo'}, class: "type-register", required: true %>
				<%= register.label :fecha_de_nacimiento %>
				<%= register.date_select :date_of_birth, { order: [:day, :month, :year], start_year: 1940, include_blank: true }, required: true %>
				<%= register.label :Eps %>
				<%= register.text_field :eps, required: true %>
				<%= register.label :correo_electrónico %>
				<%= register.text_field :email %>
			</div>
			<div class="form-group">					
				<%= register.hidden_field :_destroy %>
				<%= link_to "Borrar Participante", "#", class: "remove_field btn btn-danger" %>
			</div>
		</div>
	</div>
</fieldset>

app/views/inscriptions/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 new_register">
    	<div class="instruction-info">
		  	<h2 class="instruction-title">Por favor lea detenidamente las siguientes instrucciones antes de proceder con la inscripción.</h2>
				<ul class="instruction-list text-justify">
					<li>En cualquier momento puede cancelar el proceso de inscripción haciendo click en el boton de color rojo <strong>"Cancelar Inscripción"</strong> al final de la pagina.</li>
					<li>Para agregar un nuevo registro al formulario debe dar click en el botón naranja <strong>"Agregar Participante"</strong>, este le permitira agregar registros como sea necesario, recuerde que el limite maximo de registros es de 25, 20 para jugadores, 1 para entrenador, 3 para asistentes y un ultimo para un delegado</li>
					<li>Los campos primer nombre, primer apellido, fotografía, documento de identidad, tipo de inscripción, fecha de nacimiento, EPS, y correo electrónico son de caracter <strong>OBLIGATORIO</strong>, si alguno de esto faltara en uno de los registros, automaticamente la plataforma mostrara una X de color rojo a su lado derecho y hasta no completarlos, no se podra finalizar el proceso.</li>
					<li>Para borrar un registro previo debe dar click en el botón <strong>"Borrar Registro"</strong> que se encuentra en la parte inferior izquierda de este.</li>
					<li>Una vez termine de llenar todos los registros para guardar la inscripción debe dar clik en el botón verde <strong>"Guardar Inscripción"</strong> en la parte inferior de la página.</li>
					<li>La inscripción puede ser editada siempre y cuando no haya pasado la fecha limite de inscripción, de lo contrario la plataforma no le permitira el ingreso.</li>
				</ul>
				<p class="instruction-welcome text-center">Para la liga antioqueña de Baloncesto es un placer contar con su participacón complete el formulario para editar el registro de <%= @club.name.upcase %> en el <%= @tournament.name.upcase %></p>
			</div>
			<%= render 'inscription_form_edit' %>
		</div>
	</div>
</div>

app/views/inscriptions/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 new_register">
    	<div class="instruction-info">
		  	<h2 class="instruction-title">Porfavor lea detenidamente las siguientes instrucciones antes de proceder con la inscripción.</h2>
				<ul class="instruction-list text-justify">
					<li>En cualquier momento puede cancelar el proceso de inscripción haciendo click en el boton de color rojo <strong>"Cancelar Inscripción"</strong> al final de la pagina.</li>
					<li>Para agregar un nuevo registro al formulario debe dar click en el botón naranja <strong>"Agregar Participante"</strong>, este le permitira agregar registros como sea necesario, recuerde que el limite maximo de registros es de 25, 20 para jugadores, 1 para entrenador, 3 para asistentes y un ultimo para un delegado</li>
					<li>Los campos primer nombre, primer apellido, fotografía, documento de identidad <strong>(Solo ingrese números sin espacios)</strong>, tipo de inscripción, fecha de nacimiento, EPS, y correo electrónico son de caracter <strong>OBLIGATORIO</strong>, si alguno de esto faltara en uno de los registros, automaticamente la plataforma mostrara una X de color rojo a su lado derecho y hasta no completarlos, no se podra finalizar el proceso.</li>
					<li>Para borrar un registro previo debe dar click en el botón <strong>"Borrar Registro"</strong> que se encuentra en la parte inferior izquierda de este.</li>
					<li>Una vez termine de llenar todos los registros para guardar la inscripción debe dar clik en el botón verde <strong>"Guardar Inscripción"</strong> en la parte inferior de la página.</li>
					<li>La inscripción puede ser editada siempre y cuando no haya pasado la fecha limite de inscripción, de lo contrario la plataforma no le permitira el ingreso.</li>
				</ul>
				<p class="instruction-welcome text-center">Para la Liga antioqueña de Baloncesto es un placer contar con su participacón complete el formulario para registar a <%= @club.name.upcase %> en el <%= @tournament.name.upcase %></p>
			</div>
			<%= render 'inscription_form' %>
		</div>
	</div>
</div>

app/views/inscriptions/select_inscription.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<div class="instruction-info">
		  	<h2 class="instruction-title">Porfavor lea detenidamente las siguientes instrucciones antes de proceder con la inscripción.</h2>
				<ul class="instruction-list text-justify">
					<li>La siguiente lista contiene los torneos de la Liga Antioqueña de Baloncesto para el año 2015</li>
					<li>Los torneos con sombra verde indican que el club tiene alguna inscripción en curso a diferencia de la sombra roja que indica que el club no tiene ninguna inscripción en curso en dicho evento.</li>
					<li>Para inscribirse a un nuevo torneo haga click en el botón de color verde "Realizar Inscripción" que sera visible en la columna opciones siempre y cuando la fecha limite de inscripción no haya pasado.</li>
					<li>Una vez haya realizado una inscripción desde aqui podra verla, editarla o eliminarla con los botones que se encuentran en la columna opciones.</li>
				</ul>
			</div>
		</div>
		<table class="table table-hover">
			<tr>
				<th class="text-center">TORNEO</th>
				<th class="text-center">ESTADO DEL CLUB</th>
				<th class="text-center">FECHA LIMITE INSCRIPCION(AA-MM-DD)</th>
				<th class="text-center">ESTADO DE INSCRIPCIÓN</th>
				<th class="text-center">OPCIONES</th>
			</tr>
			<% Tournament.where(status: true).each do |tournament| %>
				<% if @inscriptions.pluck(:tournament_id).include?(tournament.id) %>
					<tr class="success">
						<td class="text-center vert-align"><%= tournament.name %></td>
						<td class="text-center vert-align"><strong>INSCRITO</strong></td>
						<td class="text-center vert-align"><strong><%= tournament.deadline %></strong></td>
							<% if tournament.expired? %>
								<td class="text-center vert-align"><strong>CERRADA</strong></td>
								<td class="text-center vert-align">
									<%= link_to "Ver", @inscriptions.find_by_tournament_id(tournament.id) , class: "btn btn-primary" %>
								</td>
							<% else %>
								<td class="text-center vert-align"><strong>ABIERTA</strong></td>
								<td class="text-center vert-align">
									<%= link_to "Ver", @inscriptions.find_by_tournament_id(tournament.id) , class: "btn btn-primary" %>
									<%= link_to "Editar", edit_inscription_path(@inscriptions.find_by_tournament_id(tournament.id), :tournament_id => "#{tournament.id}", :club_id=> "#{current_user.club.id}"), class: "btn btn-warning" if current_user.user? %>
									<%= link_to "Editar", edit_inscription_path(@inscriptions.find_by_tournament_id(tournament.id), :tournament_id => "#{tournament.id}", :club_id=> @club_id), class: "btn btn-warning" if current_user.admin? %>
									<%= link_to inscription_path(@inscriptions.find_by_tournament_id(tournament.id)), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar esta inscripción?' }, class: "btn btn-danger" do %><span>Eliminar</span><% end %>
								</td>
							<% end %>
					</tr>
				<% else %>
					<% if tournament.expired? %>
						<tr class="danger">
							<td class="text-center vert-align"><%= tournament.name %></td>
							<td class="text-center vert-align"><strong>NO INSCRITO</strong></td>
							<td class="text-center vert-align"><strong><%= tournament.deadline %></strong></td>
							<td class="text-center vert-align"><strong>CERRADA</strong></td>
							<td class="text-center vert-align"><strong>NO HAY OPCIONES</strong></td>
						</tr>
					<% else %>
						<tr class="danger">
							<td class="text-center vert-align"><%= link_to "#{tournament.name}", inscription_welcome_path(:tournament_id => "#{tournament.id}", :club_id=> "#{current_user.club.id}" ) if current_user.user? %><%= link_to "#{tournament.name}", inscription_welcome_path(:tournament_id => "#{tournament.id}", :club_id=> @club_id ) if current_user.admin? %></td>
							<td class="text-center vert-align"><strong>NO INSCRITO</strong></td>
							<td class="text-center vert-align"><strong><%= tournament.deadline %></strong></td>
							<td class="text-center vert-align"><strong>ABIERTA</strong></td>
							<td class="text-center vert-align">
								<%= link_to "Realizar Inscripción", inscription_welcome_path(:tournament_id => "#{tournament.id}", :club_id=> "#{current_user.club.id}" ), class: "btn btn-success" if current_user.user? %>
								<%= link_to "Realizar Inscripción", inscription_welcome_path(:tournament_id => "#{tournament.id}", :club_id=> @club_id ), class: "btn btn-success" if current_user.admin? %>
							</td>
						</tr>
					<% end %>
				<% end %>
			<% end %>
		</table>
	</div>
</div>

app/views/inscriptions/show.html.erb
<div class="container-fluid">
	<div class="row">
		<h2 class="text-center">Inscripción del club <%= @club.name %> a <%= @tournament.name %> </h2>
	</div>
	<div class="row">
		<table class="table table-hover">
			<tr class="info">
				<th class="text-center">Imagen</th>								
				<th class="text-center">Participante</th>
				<th class="text-center">Tipo Inscripción</th>
				<th class="text-center">Documento de Identidad</th>
				<th class="text-center">Fecha de Nacimiento</th>
				<th class="text-center">EPS</th>
				<th class="text-center">Email</th>
			</tr>
			<% @inscription.registers.each do |register| %>
				<tr class="text-center">
					<td class="vert-align"><%= image_tag register.avatar.url(:thumb) %></td>
					<td class="text-left vert-align"><%= register.first_name %> <%= register.second_name %> <%= register.first_last_name %> <%= register.second_last_name %></td>
					<td class="vert-align"><%= register.register_type.name %></td>
					<td class="vert-align"><%= register.identification %></td>
					<td class="vert-align"><%= register.date_of_birth %></td>
					<td class="vert-align"><%= register.eps %></td>
					<td class="vert-align"><%= register.email %></td>
				</tr>
			<% end %>
		</table>
	</div>
	<div class="row">
		<div class="col-xs-12 text-center">
			<%= link_to 'Editar Inscripción', edit_inscription_path(@inscription, :tournament_id => "#{@inscription.tournament_id}", :club_id=> @club.id), class: "btn btn-warning" %>
			<%= link_to 'Ir a inscripciones', inscription_index_path, class: "btn btn-success" if current_user.user? %>
		</div>
	</div>
</div>

app/views/inscriptions/welcome_inscription.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 new_register">
			<h1 class="text-center">INSCRIPCIÓN DE <%= @club.name.upcase %> A <%= @tournament.name.upcase %></h1>
				<p class="text-center"><strong>Descripción del torneo: </strong><%= @tournament.description %></p>
				<div class="instruction-info">
				<p class="instruction-title"><strong>IMPORTANTE: </strong>Al hacer click en realizar inscripción tenga en cuenta las siguientes recomendaciones:</p>
				<ul class="instruction-list text-justify">
					<li>La inscripción solo se puede realizar hasta la fecha limite definida para cada torneo.</li>
					<li>Una vez concluida la fecha limite, la inscripciones estara cerradas, cualquier duda o inquietud debe ser consultada directamente con la Liga Antioqueña de Baloncesto.</li>
					<li>Para cada registro los datos como primer nombre, primer apellido, fotografía, documento de identidad, tipo de inscripción, fecha de nacimiento, EPS, y correo electrónico son de caracter OBLIGATORIO para cada participante sea jugador, entrenador, asistente o delegado.</li>
					<li>Se recomienda tener todos los datos a la mano a la hora de realizar la inscripción, las fotografías deben ser tipo documento en fondo blanco, estas seran usadas para imprimir los carnets de cada equipo.</li>
				</ul>
			</div>
			<table class="table">
				<tr>
					<th class="text-center">Categoria</th>
					<th class="text-center">Fecha de Inicio</th>
					<th class="text-center">Fecha de Cierre</th>
					<th class="text-center">Fecha limite de inscripción</th>
				</tr>
				<tr class="text-center">
					<td><%= @tournament.category.name %></td>
					<td><%= @tournament.start_date %></td>
					<td><%= @tournament.end_date %></td>
					<td><%= @tournament.end_date %></td>
				</tr>
			</table>
			<div class="text-center">
				<%= link_to "Realizar Inscripción", new_inscription_path(:tournament_id => "#{@tournament.id}", :club_id=> @club.id ), class: "btn btn-lg btn-default" %>
			</div>
		</div>
	</div>
</div>

app/views/inscriptions/welcome_registration.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 new_register">
			<h1 class="text-center">INSCRIPCIÓN DE <%= @club.name.upcase %> A <%= @tournament.name.upcase %></h1>
			<h4> <%= @tournament.description %> </h4>
			<h5>Fecha de inicio: <%= @tournament.start_date %></h5>
			<h5>Fecha de cierra: <%= @tournament.end_date %></h5>
			<div class="text-center">
				<%= link_to "Realizar Inscripción", new_inscription_path(:tournament_id => "#{@tournament.id}", :club_id=> "#{current_user.club.id}" ), class: "btn btn-lg btn-default" %>
			</div>
		</div>
	</div>
</div>