config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :clubs
  resources :fields
  resources :inscriptions
  devise_for :users
  get 'inscription_welcome' => 'inscriptions#welcome_inscription'
  get 'inscription_index' => 'inscriptions#select_inscription'
  get 'admin' => 'admin#home'
  get 'search_register' => 'admin#search_register'
  get 'directors' => 'admin#manage_directors'
  get 'teams' => 'admin#teams'
  get 'coaches' => 'admin#coaches'
  get 'mosaico' => 'admin#mosaico'
  get 'analitics' => 'admin#analitics'
  get 'fields_index' => 'admin#fields'
  get 'license' => 'admin#license_creator'
  get 'inscriptions_index' => 'admin#inscriptions_index'

end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id         :integer          not null, primary key
#  field_type :integer
#  address    :string
#  club_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Field < ActiveRecord::Base
	enum field_type: [:coliseo_madera,:coliseo_baldosa,:coliseo_concreto,:coliseo_asfalto,:coliseo_sintética,:placa_baldosa,:placa_concreto,:placa_asfalto,:placa_sintética]
  belongs_to :club
  has_many :field_hours, dependent: :destroy
  accepts_nested_attributes_for :field_hours, reject_if: proc { |attributes| attributes['day_id'].blank? }, allow_destroy: true
  validates_associated :field_hours
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@fields = current_user.club.fields
	end

	def new
		@field = Field.new
		@field.field_hours.build
	end

	def create
		@club = current_user.club
		@field = Field.new(field_params)
		@field.club_id = current_user.club.id
		if @field.save
		  redirect_to fields_path
		else
		  render action: :new
		end
	end

	def edit
		@field = Field.find(params[:id])
	end

	def update
		@field = Field.find(params[:id])
		if @field.update(field_params)
			redirect_to fields_path
		end
	end

	def show
		@field = Field.find(params[:id])
	end

	def destroy
		@field = Field.find(params[:id])
		@field.destroy
		redirect_to fields_path
	end

	private
		def field_params
  		params.require(:field).permit(:id, :field_type, :address, field_hours_attributes: [ :id, :day_id, :open_hour, :closing_time, :_destroy ] )
		end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field_form.html.erb
<%= form_for(@field, :html => { :id => "fieldForm"}) do |cancha| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="field form-group">
				<%= cancha.label :tipo %><br />
				<%= cancha.select :field_type, options_for_select(Field.field_types.map {|k,v| [k.humanize,k]}, @field.field_type), {}, { :class => "form-control", required: true } %>
			</div>
			<div class="field form-group">
				<%= cancha.label :dirección %><br />
				<%= cancha.text_field :address, :class => "form-control", required: true %>
			</div>
		</div>
	</div>
	<div class="row text-center">
		<%= cancha.fields_for :field_hours do |h| %>
			<%= render 'field_hour_form', :hour => h %>
		<% end %>
	</div>
	<div class="actions form-group text-center">
		<%= link_to_add_fields "Agregar Horario", cancha, :field_hours %>
		<%= link_to "Cancelar", fields_path, class: "btn btn-danger" %>
	  <%= cancha.submit "Guardar Informacion de la cancha", :class => 'btn btn-success' %>
	</div>
<% end %>

<script>
$(document).on("page:change", function() {
	$("#fieldForm").validate({
		errorPlacement: function(label, element) {
      label.addClass('inscription-error');
      label.insertAfter(element);
	  },
	  wrapper: 'span'
		});

	jQuery.extend(jQuery.validator.messages, {
	    required: "Este campo es obligatorio"
	});
});
</script>

app/views/fields/_field_hour_form.html.erb
<fieldset class="form-group">
	<div class="form-group">
		<%= hour.label :dia %>
		<%= hour.collection_select :day_id, Day.all, :id, :name, {prompt: 'Seleccione Dia'}, required: true %>
		<%= hour.label :hora_apertura %>
		<%= hour.time_select :open_hour, {ampm: true, minute_step: 15, :default => {:hour => '06', :minute => '00'} }, required: true %>
		<%= hour.label :hora_cierre %>
		<%= hour.time_select :closing_time, {ampm: true, minute_step: 15, :default => {:hour => '18', :minute => '00'} }, required: true %>		
		<%= hour.hidden_field :_destroy %>
		<%= link_to "Borrar Horario", "#", class: "remove_field btn btn-xs btn-danger" %>
	</div>
</fieldset>

app/views/fields/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 new_register">
			<div class="instruction-info">
		  	<h2 class="instruction-title">Porfavor lea detenidamente las siguientes instrucciones antes de agregar una cancha.</h2>
				<ul class="instruction-list text-justify">
					<li>En cualquier momento puede cancelar el proceso haciendo click en el boton de color rojo <strong>"Cancelar"</strong> al final de la pagina.</li>
					<li>Para agregar un nuevo horario al formulario debe dar click en el botón naranja <strong>"Agregar Horario"</strong>, este le permitira agregar tantos horarios como sea necesario, no hay limite de horarios. En un horario debe indicar el día la hora de apertura y la hora de cierre para usar la cancha.</li>
					<li>Todos los campos son <strong>OBLIGATORIOS</strong>, si alguno de esto faltara, automaticamente la plataforma mostrara un mensaje de color rojo y hasta no completarlos, no se podra finalizar el registro de la cancha.</li>
					<li>Para borrar un horario debe dar click en el botón rojo <strong>"Borrar Horario"</strong> que se encuentra en la parte derecha de cada uno de estos.</li>
					<li>Una vez termine de llenar todos los registros para guardar la cancha debe dar clik en el botón verde <strong>"Guardar Información de la cancha"</strong> en la parte inferior de la página.</li>
				</ul>				
			</div>
			<h1 class="text-center">EDITAR INFORMACIÓN DE LA CANCHA</h1>
			<%= render 'field_form' %>
		</div>
	</div>
</div>

app/views/fields/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="instruction-info">
		  	<h2 class="instruction-title">Porfavor lea detenidamente las siguientes instrucciones antes de proceder con el registro de las canchas de su club.</h2>
				<ul class="instruction-list text-justify">
					<li>Para la Liga Antioqueña de Baloncesto es muy importante contar con la información de las canchas disponibles que su club o equipo poseen.</li>
					<li>Para agregar una nueva cancha haga click en el botón verde "Agregar Cancha".</li>
					<li>Una vez agregada una cancha puede verla, editarla o eliminarla desde los botones ubicados en la columna opciones.</li>
				</ul>
			</div>
		</div>
		<table class="table table-hover">
			<tr class="info">
				<th class="text-center">Tipo</th>
				<th class="text-center">Direccion</th>
				<th class="text-center">Opciones</th>			
			</tr>
			<% @fields.each do |field| %>
				<tr class="text-center">
					<td class="vert-align"><%= field.field_type.humanize %></td>
					<td class="vert-align"><%= field.address %></td>
					<td class="vert-align"><%= link_to "Ver", field, class: "btn btn-primary" %> <%= link_to "Editar", edit_field_path(field), class: "btn btn-warning" %> <%= link_to field_path(field), method: :delete, data: { confirm: '¿Esta seguro que desea elminar esta cancha?' }, class: "btn btn-danger" do %><span>Eliminar</span><% end %></td>
				</tr>
			<% end%>
		</table>
	</div>
	<div class="row text-center">
		<%= link_to 'Agregar Cancha', new_field_path, class: "btn btn-lg btn-success" %>
	</div>
</div>

app/views/fields/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 new_register">
			<div class="instruction-info">
		  	<h2 class="instruction-title">Porfavor lea detenidamente las siguientes instrucciones antes de agregar una cancha.</h2>
				<ul class="instruction-list text-justify">
					<li>En cualquier momento puede cancelar el proceso haciendo click en el boton de color rojo <strong>"Cancelar"</strong> al final de la pagina.</li>
					<li>Para agregar un nuevo horario al formulario debe dar click en el botón naranja <strong>"Agregar Horario"</strong>, este le permitira agregar tantos horarios como sea necesario, no hay limite de horarios. En un horario debe indicar el día la hora de apertura y la hora de cierre para usar la cancha.</li>
					<li>Todos los campos son <strong>OBLIGATORIOS</strong>, si alguno de esto faltara, automaticamente la plataforma mostrara un mensaje de color rojo y hasta no completarlos, no se podra finalizar el registro de la cancha.</li>
					<li>Para borrar un horario debe dar click en el botón rojo <strong>"Borrar Horario"</strong> que se encuentra en la parte derecha de cada uno de estos.</li>
					<li>Una vez termine de llenar todos los registros para guardar la cancha debe dar clik en el botón verde <strong>"Guardar Información de la cancha"</strong> en la parte inferior de la página.</li>
				</ul>				
			</div>
			<h1 class="text-center">AGREGAR UNA CANCHA DISPONIBLE</h1>
			<%= render 'field_form' %>
		</div>
	</div>
</div>

app/views/fields/show.html.erb
<div class="container new_register">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 text-center">
			<div class="col-xs-12">
				<h1>Dirección: <%= @field.address %></h1>
				<h2>Tipo: <%= @field.field_type.humanize %></h2>
			</div>
			<table class="table table-hover">
				<tr>
					<th class="text-center">No. Horario</th>
					<th class="text-center">Día</th>
					<th class="text-center">Hora de apertura</th>
					<th class="text-center">Hora de cierre</th>
				</tr>
				<% @field.field_hours.each_with_index do |field_hour, index| %>
					<tr>
						<td><%= index+1 %></td>
						<td><%= field_hour.day.name %></td>
						<td><%= field_hour.open_hour.strftime("%I:%M %p")%></td>
						<td><%= field_hour.closing_time.strftime("%I:%M %p") %></td>
					</tr>
				<% end %>
			</table>
			<div class="col-xs-4 col-xs-offset-4">
				<%= link_to 'Regresar a Canchas', fields_path, class: "btn btn-success" %>
			</div>
		</div>
	</div>
</div>