config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :clubs
  resources :fields
  resources :inscriptions
  devise_for :users
  get 'inscription_welcome' => 'inscriptions#welcome_inscription'
  get 'inscription_index' => 'inscriptions#select_inscription'
  get 'admin' => 'admin#home'
  get 'search_register' => 'admin#search_register'
  get 'directors' => 'admin#manage_directors'
  get 'teams' => 'admin#teams'
  get 'coaches' => 'admin#coaches'
  get 'mosaico' => 'admin#mosaico'
  get 'analitics' => 'admin#analitics'
  get 'fields_index' => 'admin#fields'
  get 'license' => 'admin#license_creator'
  get 'inscriptions_index' => 'admin#inscriptions_index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventos - LAB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav <% if current_page?(root_path) %>  class="navbar navbar-default navbar-fixed-top" id="navbar" <%else%> id="navbar" class="navbar navbar-default"  <%end%>>
	  <div class="container">	    
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "LAB", "#", :class => "navbar-brand", :alt => "Brand" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to 'Instrucciones', root_path %></li>
	        <li><%= link_to 'Inscripciones', inscription_index_path if user_signed_in? && current_user.club %></li>
	        <% if user_signed_in? && current_user.admin? %>
						<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones de Administrador<span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><%= link_to 'Buscar Registro', search_register_path %></li>
								<li><%= link_to 'Clubes y Directivos', directors_path %></li>
								<li><%= link_to 'Equipos Por Torneo', teams_path %></li>
								<li><%= link_to 'Entrenadores Por Torneo', coaches_path %></li>
								<li><%= link_to 'Canchas Disponibles', fields_index_path %></li>
								<li><%= link_to 'Indicadores', analitics_path %></li>
		          </ul>
		        </li>
		        <li><%= link_to 'Carnetización', inscriptions_index_path %></li>
					<% end %>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">	  
	        <% if user_signed_in? %>
						<% if current_user.club %>
							<li><%= link_to 'Ir a tu club', current_user.club if !current_page?(current_user.club) %></li>
							<li><%= link_to 'Canchas', fields_path %></li>
						<% else %>
							<li><%= link_to 'Crea tu Club', new_club_path if current_user.user? %></li>
						<% end %>
							<li><%= link_to 'Editar Cuenta', edit_user_registration_path %></li>
		        	<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
	        <% else %>
						<li><%= link_to 'Registarse', new_user_registration_path %></li>
	        <% end %>	
	      </ul>
	    </div>
	  </div>
	</nav>
  <% if flash[:alert] %>
		<div class="container-fluid">
			<div class="row">
				<div class="alert alert-danger text-center" role="alert"><%=flash[:alert]%></div>
			</div>
		</div>
  <%end%>

	<%= yield %>

	<% if current_page?(root_path) %>
		<footer>
			<div class="container-fluid">
				<div class="row footer-div">
					<div class="col-xs-12 col-sm-4 col-md-4 text-center footer-col">
						<p>Liga Antioqueña De Baloncesto</p> 
						Correo: inscripcioneseventoslab@gmail.com</br>
						Telefono: (57-4) 230 56 67 – 230 46 54</br>						
						Direccion: Cll 48 A 70-80</br>
					</div>
					<div class="col-xs-12 col-sm-4 col-md-4 text-center footer-col">
						<img src="http://ligaantioquenadebaloncesto.com/es/files/3913/6470/2828/logo_LAB.png" alt="lobo-lab" class="logo-lab" >
					</div>
					<div class="col-xs-12 col-sm-4 col-md-4 text-center footer-col">
						<p>Desarrolado Por: <%= link_to "Sebastian Zapata Mardini", "http://mardiniii.github.io",:target => "_blank" %></p>
						Email: sezama08@gmail.com</br>
						Medellin - Colombia</br>
						2015</br>
					</div>				
				</div>
			</div>
		</footer>
	<% end %>
</body>
</html>

app/views/layouts/text.html.erb
<body>
	<html>
		<%= yield %>
	</html>
</body>